spring:
  application:
    name: say-hello

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0
  
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
